### ISSUE TITLE
Term : gap

### ISSUE THREAD

**Issue by leedahee** [Display-Lab/fio#112]

**Comment by zachll** [comment]
This issue duplicates issue #24

**Comment by zachll** [comment]
*Term name - gap
*User-centered definition - A difference between data elements of a performer or measure dimension
*Comment (rdfs:comment)
*Reference - guided by Kluger, A. N., & DeNisi, A. (1996). The effects of feedback interventions on performance: A historical review, a meta-analysis, and a preliminary feedback intervention theory.
*Example Usage (IAO_0000112) - n/a, new term

**Comment by leedahee** [comment]
I may want to retrieve my opinion. 
The gap is more likely to be a difference between what a performer expect to happen and what actually happened. The point in here, I think, is the expectation or the desire. So the question might be aligned with 'Can another measure be a goal?' I would say no. 
A difference across measures of an individual time point performance summary display cannot be a goal but a indicator telling relative position, or adjustment. Even through it can be comparable, it is not a goal. I think we need a different term for the difference between measures, not expanding the existing meaning of the gap.
