### ISSUE TITLE
Term: Domain Problem

### ISSUE THREAD

**Issue by CooperStansbury** [Display-Lab/fio#124]
*Term name: domain problem
*Tentative Definition: "A part of a setting that can be **resolved** by a performance summary display"
*Reference: Needed
*Example Usage: n/a, new term

Note: document for further revision

**Comment by leedahee** [comment]
domain problem is a information needs (synonym) which can be resolved by a performance summary display

**Comment by leedahee** [comment]
![domain ontology](https://user-images.githubusercontent.com/24194372/38849821-54d8726c-41dc-11e8-870c-322f4eec25a5.jpg)
