### ISSUE TITLE
Feature Request: Separate Unique Identifiers from Dictionary in New File

### ISSUE THREAD

**Issue by CooperStansbury** [Display-Lab/fio#136]
@grosscol Is it possible to store the FIO term IRI IDs in a separate file from the term labels and definitions. (1) This will make the dictionary read more clearly and (2) this will enable me to quickly scan the 'identifier.csv' when generating new IDs for terms in FIO to avoid duplicates. I think that it would just involve adding a few lines to `make-dict.sh` and separating sparql queries into something like:

Would love to hear thoughts surrounding this. 
```
SELECT ?label ?desc
WHERE {
	?subject a owl:Class.
  ?subject rdfs:label ?label.
	?subject obo:IAO_0000115 ?desc.
}
```

and 

```
SELECT ?subject
WHERE {
	?subject a owl:Class.
  ?subject rdfs:label ?label.
	?subject obo:IAO_0000115 ?desc.
} 
```

**Comment by grosscol** [comment]
Both features are doable.

For (2) getting the current list of FIO ids, should probably bet obtained from reading fio.owl, as that is the ground truth data.  The dictionary is not guaranteed to be good nor updated.  A convenience script can be added to wrap the query you suggest.  The output could be trimmed down to just the top 10 FIO_0000000 identifiers in descending order.

For (1) the FIO identifiers are not needed for the purpose of the dictionary file? or the current formatting is distracting.  It should be easy to remove or alter the formatting.

```
### http://purl.obolibrary.org/obo/fio#FIO_0000012
```

**Comment by CooperStansbury** [comment]
For (1) reformatting might be best. I think playing down the FIO IDs, like moving them to the end to make it extremely easy and non-technical appearing. The links may be nice once we're up and running on OBO. 

For (2) absolutely agree that the terms should come from `fio-edit.owl`. Since there are not that many terms, could we just 'dump' all of them into another file? Sorted would be great.  This is just a tool to ensure that we don't re-use IDs.

**Comment by CooperStansbury** [comment]
Example formatting in #139

**Comment by CooperStansbury** [comment]
ID tool WIP in spek-terms branch. Reformatting done with PR #140
