### ISSUE TITLE
Add terms to fio-edit.owl 

### ISSUE THREAD

**Issue by CooperStansbury** [Display-Lab/fio#138]
Add the following terms to `fio-edit.owl` for the prototype. @grosscol let me know if there are any changes to this list:

performer
spek
has_performer
uses_template
uses_ISR
rid_template
spek
ISR
normative_comparator
prevention_framing
promotion_framing
performer_cardinality
time_cardinality
capability_barrier
prevention_focus
promotion_focus
negative_signal
positive_signal
perf_gap
perf_trend_pos
perf_trend_neg
related_location

**Comment by grosscol** [comment]
I was just coding `has_performers` for the spek, and I realized that has_part or any synonym of it isn't actually applicable.  The spek is about some performers, but they aren't actually a part of it.

I was thinking we might be better suited with `about_performers` or something along those lines.  I'm coding it as `has_performers` to avoid a refactor getting in the way of progress.
We might want to make that the first one we try to fit into BFO after spek, and I'll propagate the changes of whatever name we settle on at that point.

**Comment by CooperStansbury** [comment]
@grosscol @zachll  All terms and properties above have been added on branch 'spek-terms.' The dictionary on that branch is updated for quick reference.  Most terms added under superclass: 'spek terms' and will need to be placed more meaningfully once they are defined. Each term has been added with the correct annotation property and a 'dummy definition:' Definition Needed.  

I chose to add superclass terms like 'trend' to structure 'positive trend' and 'negative trend.' I created superclasses for each binary definition above. These should not affect the prototype unless you need to reason over all 'trends' rather than a specific direction of 'trend.'

I made a few modifications to terms in order ensure BFO best practices were met. These changes will affect the prototype.

1. I did not add 'perf_gap' because 'performance comparator gap' has already been added and defined `http://purl.obolibrary.org/obo/fio#FIO_0000013`. Are you able to refactor?
1. 'ISR' --> 'intervention situation response' per BFO best practice to avoid acronyms. This change was also applied to 'uses_ISR'
1. 'rid template' --> 'relational information display template' per BFO best practice to avoid acronyms.
1.  'perf_trend_pos' --> 'positive performance trend' per BFO best practice to avoid shorthand in semantic tools.
1. 'has_performer' --> 'about_performer' per your note above. 

Once we agree on the wording changes in this issue we should close and start opening more specific issues. Thoughts?

**Comment by grosscol** [comment]
The changes to the term names is fine.  The software will be using the IRIs.  The short labels are simply for human convenience.

**Comment by CooperStansbury** [comment]
These additions are all made as of PR #145
