### ISSUE TITLE
Add versionInfo annotation

### ISSUE THREAD

**Issue by grosscol** [Display-Lab/fio#143]
- Use semantic versioning scheme [semver.org](https://semver.org)
- Add versionInfo annotation

Owl's versionInfo annotation property for the ontology and a version IRI for the ontology should be all that is required.  Use semantic versioning (https://semver.org/) scheme so we can eschew the other version annotation properties provided by owl (priorVersion, backwardCompatibleWith, incompatibleWith).  Providing a version IRI should be in a different issue relating to the publishing workflow.

**Comment by CooperStansbury** [comment]
@grosscol OWL has a specific annotation property for versioning (owl:versionInfo). Do we need to have versioning information as an IRI 'inside' the ontology as well?

**Comment by grosscol** [comment]
I believe the version info annotation should be sufficient within the owl file.  The ontology IRI doesn't change.  Version IRIs just point to specific versions of the owl file that need to be made resolvable, and that is part of the publishing process.

**Comment by CooperStansbury** [comment]
added with #148
