### ISSUE TITLE
Update Licensing and FIDO Intro in README

### ISSUE THREAD

**Issue by CooperStansbury** [Display-Lab/fio#146]
@zachll I'm hoping you can:
1. Forward me a 1 - 2 paragraph description of FIDO for the REAMDE (or direct me towards a passage in previous work that I can use). I've taken a stab, but I feel strongly that your words are important here.
 1. Provide me with some information on FIDO licensing for the README (or direct me towards an appropriate resource). 

Thanks,

**Comment by CooperStansbury** [comment]
@grosscol PR #147 merged and license branch pruned.

**Comment by grosscol** [comment]
Closed by #147
