### ISSUE TITLE
Term: Feedback-Comparator Gap

### ISSUE THREAD

**Issue by john-rincon** [Display-Lab/fio#24]
*Term name - Feedback-Comparator Gap
*Definition - A numerical difference between the performance data (FIO_xxxx) of a performer (FIO_xxxx) for a performance measure (FIO_xxxx) and some comparator (FIO_xxxx)
*Comment (rdfs:comment)
*Reference - guided by Kluger, A. N., & DeNisi, A. (1996). The effects of feedback interventions on performance: A historical review, a meta-analysis, and a preliminary feedback intervention theory.
*Example Usage (IAO_0000112) - n/a, new term

**Comment by zachll** [comment]
Proposal: A feedback-comparator gap can be defined more broadly as a numerical difference between performance data of measure dimensions in addition to performer dimensions. This implies that a measures can also serve as comparators.

**Comment by leedahee** [comment]
I agree that measure and performer can be a comparator. But I also think we need two separate terms to refer to performer gap and measure gap, maybe they are subclasses. There might be different mechanisms underlying those gaps. Differentiating those gaps might be helpful when deciding which gap should be used or evaluating the effectiveness of a display with comparison.

**Comment by zachll** [comment]
OK, I reopened gap #112 to be defined as the superclass of feedback-comparator gap
