### ISSUE TITLE
Term: Trend

### ISSUE THREAD

**Issue by leedahee** [Display-Lab/fio#52]
*Term name - Trend
*Definition - a history of previous performance level?
*Comment (rdfs:comment)
*Reference - none
*Example Usage (IAO_0000112) -

**Comment by CooperStansbury** [comment]
tentative: "A difference between data elements of a performer over time."

**Comment by CooperStansbury** [comment]
Aristotelian Revision: "A data feature of difference in data elements of a performer over time."

**Comment by leedahee** [comment]
#64
