### ISSUE TITLE
Term: Time (2+) display

### ISSUE THREAD

**Issue by leedahee** [Display-Lab/fio#87]
Or, Multi-time display

Term name
Definition: A time(2+) display is a performance summary display that represents two or more time point.OR, Multi-time display is a performance summary display that make people see the trend, or past performance
Comment (rdfs:comment)
Reference: Issue #82 
Example Usage (IAO_0000112)

**Comment by john-rincon** [comment]
@leedahee - Should this be entered as a Time(2+) or multi-time display?  The same goes for Time(1) or single-time display. I think the Multi/Single sounds better and follows the convention from #86

**Comment by zachll** [comment]
Proposed new definition: A multi-time, single performer display is a single-performer display that has multiple times.

Proposed new term name: multi-time, single performer display
