### ISSUE TITLE
Term: Performance Measure

### ISSUE THREAD

**Issue by john-rincon** [Display-Lab/fio#9]
*Term name - performance measure	
*Definition - is a standard algorithm that generates performance information.
*Comment (rdfs:comment) - to-do
*Reference: L3 working paper
*Example Usage (IAO_0000112) - n/a, new term

**Comment by john-rincon** [comment]
added to ontology

**Comment by leedahee** [comment]
Most recent measure cannot explain which one is measure
<img width="555" alt="screen shot 2018-03-17 at 4 11 14 pm" src="https://user-images.githubusercontent.com/24194372/37559501-db0750b6-29fd-11e8-8ade-fe06d0908940.png">

**Comment by leedahee** [comment]
Most recent measure cannot explain which one is measure.

<img width="555" alt="screen shot 2018-03-17 at 4 11 14 pm" src="https://user-images.githubusercontent.com/24194372/37559516-10996a20-29fe-11e8-90b8-d7fde296ec60.png">
