### ISSUE TITLE
Term: P(1)T(1) Bargraph

### ISSUE THREAD

**Issue by leedahee** [Display-Lab/fio#94]
Definition: P(1)T(1) Bargraph is a performance summary display that represents single performer and single time point.
Comment (rdfs:comment)
Reference: Issue #86 #93 #89
Example Usage

**Comment by john-rincon** [comment]
Definition: P(1)T(1) Bargraph is a P(1)T(1) display that contains a bargraph. 

Notes: to make the definition Aristotelian according to the taxonomy, this alteration is necessary. 

Notes2: Will anything that contains a bargraph fall under here? What if there are multiple representations of the same data?
